title: Ruecharli
author: Rue Charli
email: contact@ruecharli.blog
description: Worldbuilding Resources, Personal Projects, and Failures

# social links
rss: Subscribe via RSS
# cguild_username: rue_cr
# twitter_username: jekyllrb
# github_username:  jekyll
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

show_excerpts: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d %R"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.md
  - search.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
