title: Ruecharli
masthead: /assets/icon.png

author: Rue Charli
email: contact@ruecharli.blog
description: Worldbuilding guides, resources, and personal projects. My aim is to lower the barriers to entry and bring some much-deserved love to the technical worldbuilding community.

# social links
rss: Subscribe via RSS
# cguild_username: rue_cr
# twitter_username: jekyllrb
# github_username:  jekyll
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

show_excerpts: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d %R (UTC+8)"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.md
  - search.md

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

production_url: "https://ruecharli.blog"

